rf-start: 2
rf-stop: 2.5
rf-step: .5
rf-freq: 2
rf-p: 0
rf-conf: './config/hp83508.yaml'
h-max: 150
h-zero: 0.1   # p.u. for zero field start and end
N: 10000
rate: 1000
name: 'fmr-test'
dir: '.' # must be terminated with a "/"
daq-dev: 'Dev1'
ai: {'field-set-measure': 'ai1', 'field-is-measure': 'ai2', 'short': 'ai3', 'x-value-lockin': 'ai0', 'y-value-lockin': 'ai4', }
ao: ['ao0']
impuls: 'ctr0'
trigger: 'Ctr0InternalOutput'
read-timeout: 30
buffer-size: 200