image: python:3.7-alpine

pages:
  stage: deploy
  script:
    - pip install -U sphinx mock 
    - cd docs && make html 
    - cp -r docs/html/ public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH