samples: 20000  # number of samples 
rate: 1000      # sample rate == frequency
name: 'test'    # output file prefix (e.g. sample name)

measurement:
  h-field:        # field boundaries      
    h-min: 0    
    h-max: 150
  rf:             # rf boundaries and steps
    f-start: 2
    f-end: 5
    f-step: 0.5
    p-dbm: 0