devices:
  rf-generator:
    id: "GPIB0::19::INSTR"
  daq-card:
    id: "Dev1"
    ai:
      field-set-measure: "ai1"
      field-is-measure: "ai2"
      x-value-lockin: "ai0"
      y-value-lockin: "ai4"
      short-circtuit: "ai3"
    ao:
      set-value-small: "ao0"
      set-value-big: "ao1"
    ctr:
      impuls-1: "ctr0"
    trigger:
      impuls-1: "Ctr0InternalOutput"

measurement:
  h-field:
    h-min: 0
    h-max: 150
  rf: 
    f-start: 2
    f-end: 5
    f-step: 0.5
    p-dbm: 0